//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonContentCancel {
            get {
                return ResourceManager.GetString("ButtonContentCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ButtonContentDownload {
            get {
                return ResourceManager.GetString("ButtonContentDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Download button to get the file.
        /// </summary>
        public static string ButtonToolTip {
            get {
                return ResourceManager.GetString("ButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After pasting YouTube link, you can select the audio quality from this list.
        /// </summary>
        public static string ComboBoxInitial {
            get {
                return ResourceManager.GetString("ComboBoxInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pusty link.
        /// </summary>
        public static string StandardOutputEmptyLink {
            get {
                return ResourceManager.GetString("StandardOutputEmptyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio and video		Best quality.
        /// </summary>
        public static string TextBoxContentInitial {
            get {
                return ResourceManager.GetString("TextBoxContentInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste link and press Enter or Download button.
        /// </summary>
        public static string TextBoxInitial {
            get {
                return ResourceManager.GetString("TextBoxInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste YouTube link and press Enter or Download button.
        /// </summary>
        public static string TextBoxYouTubeInitial {
            get {
                return ResourceManager.GetString("TextBoxYouTubeInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Downloader EN.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
