//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced information. Available YouTube file formats:.
        /// </summary>
        public static string AdvancedInformationAvailableYouTubeFileFormats {
            get {
                return ResourceManager.GetString("AdvancedInformationAvailableYouTubeFileFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio and video		 Best YouTube quality.
        /// </summary>
        public static string AudioAndVideoBestYouTubeQuality {
            get {
                return ResourceManager.GetString("AudioAndVideoBestYouTubeQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: acceptable 	 Bitrate average: 115 kbit/s, bitrate range: 095-135 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityAcceptable {
            get {
                return ResourceManager.GetString("AudioQualityAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: audio book 	 Bitrate average: 100 kbit/s, bitrate range: 080-120 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityAudioBook {
            get {
                return ResourceManager.GetString("AudioQualityAudioBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: best 	 Bitrate average: 245 kbit/s, bitrate range: 220-260 kbit/s, VBR mp3 lossy compression (Large mp3 file size).
        /// </summary>
        public static string AudioQualityBest {
            get {
                return ResourceManager.GetString("AudioQualityBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: better 	 Bitrate average: 225 kbit/s, bitrate range: 190-250 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityBetter {
            get {
                return ResourceManager.GetString("AudioQualityBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality could not be retrieved.
        /// </summary>
        public static string AudioQualityCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AudioQualityCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: good 	 Bitrate average: 130 kbit/s, bitrate range: 120-150 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityGood {
            get {
                return ResourceManager.GetString("AudioQualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: optimal 	 Bitrate average: 190 kbit/s, bitrate range: 170-210 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityOptimal {
            get {
                return ResourceManager.GetString("AudioQualityOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: raw aac 	 AAC (m4a) unprocessed.
        /// </summary>
        public static string AudioQualityRawAac {
            get {
                return ResourceManager.GetString("AudioQualityRawAac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: raw opus 	 Opus unprocessed.
        /// </summary>
        public static string AudioQualityRawOpus {
            get {
                return ResourceManager.GetString("AudioQualityRawOpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: raw vorbis 	 Vorbis unprocessed.
        /// </summary>
        public static string AudioQualityRawVorbis {
            get {
                return ResourceManager.GetString("AudioQualityRawVorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: raw webm 	 WebM (Opus) unprocessed.
        /// </summary>
        public static string AudioQualityRawWebm {
            get {
                return ResourceManager.GetString("AudioQualityRawWebm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: superb 	 FLAC lossless compression (Largest flac file size).
        /// </summary>
        public static string AudioQualitySuperb {
            get {
                return ResourceManager.GetString("AudioQualitySuperb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: transparent 	 Bitrate average: 165 kbit/s, bitrate range: 140-185 kbit/s, VBR mp3 lossy compression (Balanced mp3 file size).
        /// </summary>
        public static string AudioQualityTransparent {
            get {
                return ResourceManager.GetString("AudioQualityTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: very good 	 Bitrate average: 175 kbit/s, bitrate range: 150-195 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityVeryGood {
            get {
                return ResourceManager.GetString("AudioQualityVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: worse 	 Bitrate average: 085 kbit/s, bitrate range: 070-105 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityWorse {
            get {
                return ResourceManager.GetString("AudioQualityWorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: worst 	 Bitrate average: 065 kbit/s, bitrate range: 040-090 kbit/s, VBR mp3 lossy compression (Smallest mp3 file size).
        /// </summary>
        public static string AudioQualityWorst {
            get {
                return ResourceManager.GetString("AudioQualityWorst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonContentCancel {
            get {
                return ResourceManager.GetString("ButtonContentCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ButtonContentDownload {
            get {
                return ResourceManager.GetString("ButtonContentDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Download button to get the file.
        /// </summary>
        public static string ButtonToolTip {
            get {
                return ResourceManager.GetString("ButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After pasting YouTube link, you can select the audio quality from this list.
        /// </summary>
        public static string ComboBoxInitial {
            get {
                return ResourceManager.GetString("ComboBoxInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted files.
        /// </summary>
        public static string DeletedFiles {
            get {
                return ResourceManager.GetString("DeletedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded file size: .
        /// </summary>
        public static string DownloadedFileSize {
            get {
                return ResourceManager.GetString("DownloadedFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finished.
        /// </summary>
        public static string DownloadFinished {
            get {
                return ResourceManager.GetString("DownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download time: .
        /// </summary>
        public static string DownloadTime {
            get {
                return ResourceManager.GetString("DownloadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. No file downloaded. Updates are needed.
        /// </summary>
        public static string ErrorNoFileDownloadedUpdatesAreNeeded {
            get {
                return ResourceManager.GetString("ErrorNoFileDownloadedUpdatesAreNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. No Internet connection. No file downloaded.
        /// </summary>
        public static string ErrorNoInternetConnectionNoFileDownloaded {
            get {
                return ResourceManager.GetString("ErrorNoInternetConnectionNoFileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception. Google Sheets update failed.
        /// </summary>
        public static string ExceptionUpdatingWebhookFailed {
            get {
                return ResourceManager.GetString("ExceptionUpdatingWebhookFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has already been downloaded.
        /// </summary>
        public static string FileHasAlreadyBeenDownloaded {
            get {
                return ResourceManager.GetString("FileHasAlreadyBeenDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finished.
        /// </summary>
        public static string FinishedMessageDownloadFinished {
            get {
                return ResourceManager.GetString("FinishedMessageDownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finished. Now transcoding to FLAC. This may take a while. Processing.
        /// </summary>
        public static string FinishedMessageDownloadFinishedFlac {
            get {
                return ResourceManager.GetString("FinishedMessageDownloadFinishedFlac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finished. Now transcoding to mp3. This may take a while. Processing.
        /// </summary>
        public static string FinishedMessageDownloadFinishedMp3 {
            get {
                return ResourceManager.GetString("FinishedMessageDownloadFinishedMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection reestablished.
        /// </summary>
        public static string InternetConnectionReestablished {
            get {
                return ResourceManager.GetString("InternetConnectionReestablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file downloaded. Unsupported website.
        /// </summary>
        public static string NoFileDownloadedUnsupportedWebsite {
            get {
                return ResourceManager.GetString("NoFileDownloadedUnsupportedWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid link.
        /// </summary>
        public static string NotValidLink {
            get {
                return ResourceManager.GetString("NotValidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press button to get online help..
        /// </summary>
        public static string PressButtonToGetOnlineHelp {
            get {
                return ResourceManager.GetString("PressButtonToGetOnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing time: .
        /// </summary>
        public static string ProcessingTime {
            get {
                return ResourceManager.GetString("ProcessingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio: .
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed files.
        /// </summary>
        public static string RenamedFiles {
            get {
                return ResourceManager.GetString("RenamedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting application.
        /// </summary>
        public static string RestartingApplication {
            get {
                return ResourceManager.GetString("RestartingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roundtrip time 	   |           .
        /// </summary>
        public static string RoundtripTime {
            get {
                return ResourceManager.GetString("RoundtripTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending of an Internet Control Message Protocol not successful.
        /// </summary>
        public static string SendingOfAnInternetControlMessageProtocolNotSuccessful {
            get {
                return ResourceManager.GetString("SendingOfAnInternetControlMessageProtocolNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending of an Internet Control Message Protocol successful.
        /// </summary>
        public static string SendingOfAnInternetControlMessageProtocolSuccessful {
            get {
                return ResourceManager.GetString("SendingOfAnInternetControlMessageProtocolSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software 	   |	Version.
        /// </summary>
        public static string SoftwareVersion {
            get {
                return ResourceManager.GetString("SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        public static string StandardOutputCheckingForUpdates {
            get {
                return ResourceManager.GetString("StandardOutputCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading new Audio Downloader version.
        /// </summary>
        public static string StandardOutputDownloadingNewAudioDownloaderVersion {
            get {
                return ResourceManager.GetString("StandardOutputDownloadingNewAudioDownloaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading new Youtube-dl version.
        /// </summary>
        public static string StandardOutputDownloadingNewYoutubeDlVersion {
            get {
                return ResourceManager.GetString("StandardOutputDownloadingNewYoutubeDlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty link.
        /// </summary>
        public static string StandardOutputEmptyLink {
            get {
                return ResourceManager.GetString("StandardOutputEmptyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. No internet connection.
        /// </summary>
        public static string StandardOutputNoInternetConnection {
            get {
                return ResourceManager.GetString("StandardOutputNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StandardOutputReady {
            get {
                return ResourceManager.GetString("StandardOutputReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready. Updated Youtube-dl to latest version.
        /// </summary>
        public static string StandardOutputReadyUpdatedYoutubeDlToLatestVersion {
            get {
                return ResourceManager.GetString("StandardOutputReadyUpdatedYoutubeDlToLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving quality.
        /// </summary>
        public static string StandardOutputRetrievingQuality {
            get {
                return ResourceManager.GetString("StandardOutputRetrievingQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube link is invalid.
        /// </summary>
        public static string StandardOutputYouTubeLinkIsInvalid {
            get {
                return ResourceManager.GetString("StandardOutputYouTubeLinkIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting download....
        /// </summary>
        public static string StartingDownload {
            get {
                return ResourceManager.GetString("StartingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application initialized.
        /// </summary>
        public static string StatusLogApplicationInitialized {
            get {
                return ResourceManager.GetString("StatusLogApplicationInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration updated.
        /// </summary>
        public static string StatusLogConfigurationUpdated {
            get {
                return ResourceManager.GetString("StatusLogConfigurationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished download.
        /// </summary>
        public static string StatusLogFinishedDownload {
            get {
                return ResourceManager.GetString("StatusLogFinishedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting download of the link: .
        /// </summary>
        public static string StatusLogStartingDownloadOfTheLink {
            get {
                return ResourceManager.GetString("StatusLogStartingDownloadOfTheLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio and video 		 Best quality.
        /// </summary>
        public static string TextBoxContentInitial {
            get {
                return ResourceManager.GetString("TextBoxContentInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste link and press Enter or Download button.
        /// </summary>
        public static string TextBoxInitial {
            get {
                return ResourceManager.GetString("TextBoxInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste YouTube link and press Enter or Download button.
        /// </summary>
        public static string TextBoxYouTubeInitial {
            get {
                return ResourceManager.GetString("TextBoxYouTubeInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string ThreadPoolWorkerAt {
            get {
                return ResourceManager.GetString("ThreadPoolWorkerAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ThreadPoolWorkerDownload {
            get {
                return ResourceManager.GetString("ThreadPoolWorkerDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading webpage.
        /// </summary>
        public static string ThreadPoolWorkerDownloadingWebpage {
            get {
                return ResourceManager.GetString("ThreadPoolWorkerDownloadingWebpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA.
        /// </summary>
        public static string ThreadPoolWorkerEta {
            get {
                return ResourceManager.GetString("ThreadPoolWorkerEta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of .
        /// </summary>
        public static string ThreadPoolWorkerOf {
            get {
                return ResourceManager.GetString("ThreadPoolWorkerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left mouse click: opens download folder
        ///Right mouse click: chooses download folder
        ///Current download folder:.
        /// </summary>
        public static string ToolTipFolder {
            get {
                return ResourceManager.GetString("ToolTipFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcoded file size: .
        /// </summary>
        public static string TranscodedFileSize {
            get {
                return ResourceManager.GetString("TranscodedFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzipped files.
        /// </summary>
        public static string UnzippedFiles {
            get {
                return ResourceManager.GetString("UnzippedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed. Click here to download the update manually.
        /// </summary>
        public static string UpdateFailedClickHereToDownloadManually {
            get {
                return ResourceManager.GetString("UpdateFailedClickHereToDownloadManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed. Increase timeout in AudioDownloader.exe.Config and restart application or click here to download manually.
        /// </summary>
        public static string UpdateFailedIncreaseTimeoutClickHereToDownloadManually {
            get {
                return ResourceManager.GetString("UpdateFailedIncreaseTimeoutClickHereToDownloadManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Audio Downloader.
        /// </summary>
        public static string UpdaterClosingAudioDownloader {
            get {
                return ResourceManager.GetString("UpdaterClosingAudioDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting old files.
        /// </summary>
        public static string UpdaterDeletingOldFiles {
            get {
                return ResourceManager.GetString("UpdaterDeletingOldFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update. Please download the latest version manually from: https://chriskolan.github.io/audio-downloader.
        /// </summary>
        public static string UpdaterFailedToUpdate {
            get {
                return ResourceManager.GetString("UpdaterFailedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing update.
        /// </summary>
        public static string UpdaterFinishingUpdate {
            get {
                return ResourceManager.GetString("UpdaterFinishingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Audio Downloader.
        /// </summary>
        public static string UpdaterStartingAudioDownloader {
            get {
                return ResourceManager.GetString("UpdaterStartingAudioDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Audio Downloader.
        /// </summary>
        public static string UpdaterUpdatingAudioDownloader {
            get {
                return ResourceManager.GetString("UpdaterUpdatingAudioDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube link not valid.
        /// </summary>
        public static string ValidationYouTubeLinkNotValid {
            get {
                return ResourceManager.GetString("ValidationYouTubeLinkNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for automatic download.
        /// </summary>
        public static string ViewCheckForAutomaticDownload {
            get {
                return ResourceManager.GetString("ViewCheckForAutomaticDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for clipboard capture.
        /// </summary>
        public static string ViewCheckForClipboardCapture {
            get {
                return ResourceManager.GetString("ViewCheckForClipboardCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for download of best quality audio and video on youtube-dl supported websites.
        /// </summary>
        public static string ViewCheckForDownloadOnSupportedWebsites {
            get {
                return ResourceManager.GetString("ViewCheckForDownloadOnSupportedWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for using last selected quality.
        /// </summary>
        public static string ViewCheckForUsingLastSelectedQuality {
            get {
                return ResourceManager.GetString("ViewCheckForUsingLastSelectedQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose audio quality of the file.
        /// </summary>
        public static string ViewChooseAudioQualityOfTheFile {
            get {
                return ResourceManager.GetString("ViewChooseAudioQualityOfTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Downloader.
        /// </summary>
        public static string ViewWindowTitle {
            get {
                return ResourceManager.GetString("ViewWindowTitle", resourceCulture);
            }
        }
    }
}
