//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio and video 		 Best YouTube quality.
        /// </summary>
        public static string AudioAndVideoBestYouTubeQuality {
            get {
                return ResourceManager.GetString("AudioAndVideoBestYouTubeQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: acceptable 	 Bitrate average: 115 kbit/s, bitrate range: 100-130 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityAcceptable {
            get {
                return ResourceManager.GetString("AudioQualityAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: audio book 	 Bitrate average: 100 kbit/s, bitrate range: 080-120 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityAudioBook {
            get {
                return ResourceManager.GetString("AudioQualityAudioBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: best 	 Bitrate average: 245 kbit/s, bitrate range: 220-260 kbit/s, VBR mp3 lossy compression (Large mp3 file size).
        /// </summary>
        public static string AudioQualityBest {
            get {
                return ResourceManager.GetString("AudioQualityBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: better 	 Bitrate average: 225 kbit/s, bitrate range: 190-250 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityBetter {
            get {
                return ResourceManager.GetString("AudioQualityBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: good 	 Bitrate average: 130 kbit/s, bitrate range: 120-150 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityGood {
            get {
                return ResourceManager.GetString("AudioQualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: optimal 	 Bitrate average: 190 kbit/s, bitrate range: 170-210 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityOptimal {
            get {
                return ResourceManager.GetString("AudioQualityOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: raw aac 	 AAC (m4a) unprocessed.
        /// </summary>
        public static string AudioQualityRawAac {
            get {
                return ResourceManager.GetString("AudioQualityRawAac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: raw opus 	 Opus unprocessed.
        /// </summary>
        public static string AudioQualityRawOpus {
            get {
                return ResourceManager.GetString("AudioQualityRawOpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: raw vorbis 	 Vorbis unprocessed.
        /// </summary>
        public static string AudioQualityRawVorbis {
            get {
                return ResourceManager.GetString("AudioQualityRawVorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: raw webm 	 WebM (Opus) unprocessed.
        /// </summary>
        public static string AudioQualityRawWebm {
            get {
                return ResourceManager.GetString("AudioQualityRawWebm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: superb 	 FLAC lossless compression (Largest flac file size).
        /// </summary>
        public static string AudioQualitySuperb {
            get {
                return ResourceManager.GetString("AudioQualitySuperb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: transparent 	 Bitrate average: 165 kbit/s, bitrate range: 140-185 kbit/s, VBR mp3 lossy compression (Balanced mp3 file size).
        /// </summary>
        public static string AudioQualityTransparent {
            get {
                return ResourceManager.GetString("AudioQualityTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: very good 	 Bitrate average: 175 kbit/s, bitrate range: 150-195 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityVeryGood {
            get {
                return ResourceManager.GetString("AudioQualityVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: worse 	 Bitrate average: 085 kbit/s, bitrate range: 070-105 kbit/s, VBR mp3 lossy compression.
        /// </summary>
        public static string AudioQualityWorse {
            get {
                return ResourceManager.GetString("AudioQualityWorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality: worst 	 Bitrate average: 065 kbit/s, bitrate range: 045-085 kbit/s, VBR mp3 lossy compression (Smallest mp3 file size).
        /// </summary>
        public static string AudioQualityWorst {
            get {
                return ResourceManager.GetString("AudioQualityWorst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonContentCancel {
            get {
                return ResourceManager.GetString("ButtonContentCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ButtonContentDownload {
            get {
                return ResourceManager.GetString("ButtonContentDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Download button to get the file.
        /// </summary>
        public static string ButtonToolTip {
            get {
                return ResourceManager.GetString("ButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After pasting YouTube link, you can select the audio quality from this list.
        /// </summary>
        public static string ComboBoxInitial {
            get {
                return ResourceManager.GetString("ComboBoxInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pusty link.
        /// </summary>
        public static string StandardOutputEmptyLink {
            get {
                return ResourceManager.GetString("StandardOutputEmptyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StandardOutputReady {
            get {
                return ResourceManager.GetString("StandardOutputReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio and video 		 Best quality.
        /// </summary>
        public static string TextBoxContentInitial {
            get {
                return ResourceManager.GetString("TextBoxContentInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste link and press Enter or Download button.
        /// </summary>
        public static string TextBoxInitial {
            get {
                return ResourceManager.GetString("TextBoxInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste YouTube link and press Enter or Download button.
        /// </summary>
        public static string TextBoxYouTubeInitial {
            get {
                return ResourceManager.GetString("TextBoxYouTubeInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Downloader EN.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
